[project]
name = "bailian-asr"
version = "0.1.0"
description = "阿里云百炼ASR处理器"
dependencies = [
    "dashscope>=1.23.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"